function cfgShow

global CFG

cfgWinHdl = findobj('Tag',CFG.CFG_TAGS{2});

if isempty(cfgWinHdl)
    cfgWinHdl = figure('Tag', CFG.CFG_TAGS{2},...
        'Name', 'cfg_datatool',...
        'MenuBar', 'none',...
        'NumberTitle', 'off', ...
        'Resize', 'off',...
        'Color', [.95 1 .95]);
    %     'CloseRequestFcn','ilabShowSaccadeTblCB(''close'')');
    
    scrsz = get(0,'ScreenSize');
    S = get(gcf, 'Position'); % Position of default figure
    S(2) =   0.15*scrsz(4);      % bottom
    S(3) = 1.4*S(3);  % width
    S(4) = 0.85*scrsz(4);   % height
    set(gcf, 'Position', S);
    
    BgColor1 = [.95 1 .95];
    BgColor2 = [1 1 .95];
    
    % Menu Items
    m = uimenu(cfgWinHdl, 'Label', 'File', 'Tag', CFG.CFG_MTAGS{1}{1});
    uimenu(m, 'Label', 'Import trial data', 'Tag', CFG.CFG_MTAGS{1}{2}, 'Callback','');
    hEx = uimenu(m, 'Label', 'Export...', 'Tag', CFG.CFG_MTAGS{1}{3}, 'Callback','');
    uimenu(hEx, 'Label', 'cfg_datatool saccades', 'Tag', CFG.CFG_MTAGS{1}{4}, 'Callback','');
    uimenu(hEx, 'Label', 'Original saccades', 'Tag', CFG.CFG_MTAGS{1}{5}, 'Callback','');
    uimenu(hEx, 'Label', 'All saccades', 'Tag', CFG.CFG_MTAGS{1}{6}, 'Callback','');
    uimenu(hEx, 'Label', 'Auto-saccade parameters', 'Tag', CFG.CFG_MTAGS{1}{7}, 'Callback','');
    uimenu(m, 'Label', 'Save cfg_datatool workspace', 'Tag', CFG.CFG_MTAGS{1}{8}, 'Callback','');
    uimenu(m, 'Label', 'Load cfg_datatool workspace', 'Tag', CFG.CFG_MTAGS{1}{9}, 'Callback','');
    uimenu(m, 'Label', 'Exit', 'Separator', 'on', 'Tag', CFG.CFG_MTAGS{1}{10}, 'Callback','');
    
    m = uimenu(cfgWinHdl, 'Label', 'Edit', 'Tag', CFG.CFG_MTAGS{2}{1});
    uimenu(m, 'Label', 'Parameters', 'Tag', CFG.CFG_MTAGS{2}{2},'Callback','');
    
    m = uimenu(cfgWinHdl, 'Label', 'Saccade', 'Tag', CFG.CFG_MTAGS{3}{1});
    uimenu(m, 'Label', 'Select', 'Tag', CFG.CFG_MTAGS{3}{2}, 'Callback','cfgSaccCB(''select'')');
    uimenu(m, 'Label', 'Add', 'Tag', CFG.CFG_MTAGS{3}{3},'Callback','');
    uimenu(m, 'Label', 'Modify', 'Tag', CFG.CFG_MTAGS{3}{4},'Callback','');
    uimenu(m, 'Label', 'Drop', 'Separator', 'on', 'Tag', CFG.CFG_MTAGS{3}{5},'Callback','');
    uimenu(m, 'Label', 'Error', 'Tag', CFG.CFG_MTAGS{3}{6},'Callback','');
    
    m = uimenu(cfgWinHdl, 'Label', 'Plot', 'Tag', CFG.CFG_MTAGS{4}{1});
    uimenu(m, 'Label', 'Plot all', 'Tag', CFG.CFG_MTAGS{4}{2}, 'Callback','');
    
    m = uimenu(cfgWinHdl, 'Label', 'Analysis', 'Tag', CFG.CFG_MTAGS{5}{1});
    
    m = uimenu(cfgWinHdl, 'Label', 'About', 'Tag', CFG.CFG_MTAGS{6}{1});
    uimenu(m, 'Label', 'Toolbox help', 'Tag', CFG.CFG_MTAGS{6}{2}, 'Callback','');
    uimenu(m, 'Label', 'About cfg_datatool', 'Separator', 'on', 'Tag', CFG.CFG_MTAGS{6}{3}, 'Callback','');
    
    % Left side, upper text
    hLp = uipanel('Parent',cfgWinHdl,...
        'Title','General Info',...
        'FontWeight', 'Bold',...
        'BackgroundColor',BgColor1,...
        'Units','normalized','Position',[.01 .8 .49 .2]);
    
    hSubjectText = uicontrol(hLp,'Style','text',...
        'Tag', CFG.CFG_TAGS{3},...
        'Units','normalized','Position',[.01 .7 .9 .2],...
        'HorizontalAlignment', 'left',...
        'BackgroundColor',BgColor1,...
        'String',['Subject: ' CFG.subject]);
    
    hDateText = uicontrol(hLp,'Style','text',...
        'Tag', CFG.CFG_TAGS{4},...
        'Units','normalized','Position',[.01 .5 .9 .2],...
        'HorizontalAlignment', 'left',...
        'BackgroundColor',BgColor1,...
        'String',['Date: ' CFG.date]);

    hTimeText = uicontrol(hLp,'Style','text',...
        'Tag', CFG.CFG_TAGS{5},...
        'Units','normalized','Position',[.01 .3 .9 .2],...
        'HorizontalAlignment', 'left',...
        'BackgroundColor',BgColor1,...
        'String',['Time: ' CFG.time]);
    
    hTimeText = uicontrol(hLp,'Style','text',...
        'Tag', CFG.CFG_TAGS{6},...
        'Units','normalized','Position',[.01 .1 .9 .2],...
        'HorizontalAlignment', 'left',...
        'BackgroundColor',BgColor1,...
        'String',['Path: ' CFG.path]);

    % Right side, upper text
    hRp = uipanel('Parent',cfgWinHdl,...
        'Title','Trial Info',...
        'FontWeight', 'Bold',...
        'BackgroundColor',BgColor1,...
        'Units','normalized','Position',[.51 .8 .49 .2]);
    
    hTrialsText = uicontrol(hRp,'Style','text',...
        'Tag', CFG.CFG_TAGS{7},...
        'Units','normalized','Position',[.01 .7 .9 .2],...
        'HorizontalAlignment', 'left',...
        'BackgroundColor',BgColor1,...
        'String',['Number of Trials: ' int2str(CFG.trials)]);
    
    hDropText = uicontrol(hRp,'Style','text',...
        'Tag', CFG.CFG_TAGS{8},...
        'Units','normalized','Position',[.01 .5 .9 .2],...
        'HorizontalAlignment', 'left',...
        'BackgroundColor',BgColor1,...
        'String',['Number of Dropped Trials: ' int2str(length(find(CFG.drop)))]); % Callback?

    hErrText = uicontrol(hRp,'Style','text',...
        'Tag', CFG.CFG_TAGS{9},...
        'Units','normalized','Position',[.01 .3 .9 .2],...
        'HorizontalAlignment', 'left',...
        'BackgroundColor',BgColor1,...
        'String',['Number of Error Trials: ' int2str(length(find(CFG.err)))]); % Callback?
    
    % Lower UI items
    hInitialHeader = uicontrol(cfgWinHdl,'Style','text',...
        'Tag', CFG.CFG_TAGS{10},...
        'Units','normalized','Position',[.01 .75 .49 .04],...
        'HorizontalAlignment', 'left',...
        'String',CFG.tTitle,...
        'BackgroundColor',BgColor2,...
        'FontWeight', 'bold');
    
    hFinalHeader = uicontrol(cfgWinHdl,'Style','text',...
        'Tag', CFG.CFG_TAGS{11},...
        'Units','normalized','Position',[.51 .75 .49 .04],...
        'HorizontalAlignment', 'left',...
        'String',CFG.tTitle,...
        'BackgroundColor',BgColor2,...
        'FontWeight', 'bold');
    
    hInitialListBox = uicontrol(cfgWinHdl,'Style','listbox',...
        'Tag', CFG.CFG_TAGS{12},...
        'Units','normalized','Position',[.01 .01 .49 .75],...
        'String',CFG.initial.table,...
        'BackgroundColor',BgColor2,...
        'Min', 0, 'Max', 1);
%         'Fontname', FWFONTNAME,...
%         'CallBack','');
        
    hFinalListBox = uicontrol(cfgWinHdl,'Style','listbox',...
        'Tag', CFG.CFG_TAGS{13},...
        'Units','normalized','Position',[.51 .01 .49 .75],...
        'String',CFG.final.table,...
        'BackgroundColor',BgColor2,...
        'Min', 0, 'Max', 1);
%         'Fontname', FWFONTNAME,...
%         'CallBack','');

end

figure(cfgWinHdl);

end