function cfgShow

global CFG

cfgWinHdl = findobj('Tag',CFG.CFG_TAGS{2});

if isempty(cfgWinHdl)
    cfgWinHdl = figure('Tag', CFG.CFG_TAGS{2},...
        'Name', 'cfg_datatool',...
        'NumberTitle', 'off', ...
        'MenuBar', 'none',...
        'Color', [.95 1 .95]);
    %     'CloseRequestFcn','ilabShowSaccadeTblCB(''close'')');
    
    scrsz = get(0,'ScreenSize');
    S = get(gcf, 'Position'); % Position of ilab (UI cfgShow will always get called from)
    S(2) =   0.1*scrsz(4);      % bottom
    S(3) = 1.2*S(3);  % width
    S(4) = 0.80*scrsz(4);   % height
    set(gcf, 'Position', S);
    
    acqIntvl = ilabGetAcqIntvl;
    
    hInitialListBox = uicontrol(cfgWinHdl,'Style','listbox',...
        'Tag', CFG.CFG_TAGS{3},...
        'Units','normalized','Position',[.01 .01 .49 .7],...
        'String',CFG.initial.table,...
        'BackgroundColor',[1 1 .95],...
        'Min', 0, 'Max', 2);
%         'Fontname', FWFONTNAME,...
%         'CallBack','');
        
    hFinalListBox = uicontrol(cfgWinHdl,'Style','listbox',...
        'Tag', CFG.CFG_TAGS{4},...
        'Units','normalized','Position',[.51 .01 .49 .7],...
        'String',CFG.final.table,...
        'BackgroundColor',[1 1 .95],...
        'Min', 0, 'Max', 2);
%         'Fontname', FWFONTNAME,...
%         'CallBack','');

end

figure(cfgWinHdl);

end