function cfgShow

global CFG

cfgWinHdl = findobj('Tag',CFG.CFG_TAGS{2});

if isempty(cfgWinHdl)
    cfgWinHdl = figure('Tag', CFG.CFG_TAGS{2},...
        'Name', 'cfg_datatool',...
        'MenuBar', 'none',...
        'NumberTitle', 'off', ...
        'Resize', 'off',...
        'Color', [.95 1 .95]);
    %     'CloseRequestFcn','ilabShowSaccadeTblCB(''close'')');
    
    scrsz = get(0,'ScreenSize');
    S = get(gcf, 'Position'); % Position of default figure
    S(2) =   0.15*scrsz(4);      % bottom
    S(3) = 1.4*S(3);  % width
    S(4) = 0.85*scrsz(4);   % height
    set(gcf, 'Position', S);
    
    BgColor1 = [.95 1 .95];
    BgColor2 = [1 1 .95];
    
    % Menu Items
    uimenu(cfgWinHdl, 'Label', 'File', 'Tag', CFG.CFG_TAGS{3});
    uimenu(cfgWinHdl, 'Label', 'Edit', 'Tag', CFG.CFG_TAGS{4});
    uimenu(cfgWinHdl, 'Label', 'Saccade', 'Tag', CFG.CFG_TAGS{5});
    uimenu(cfgWinHdl, 'Label', 'Plot', 'Tag', CFG.CFG_TAGS{6});
    uimenu(cfgWinHdl, 'Label', 'Analysis', 'Tag', CFG.CFG_TAGS{7});
    uimenu(cfgWinHdl, 'Label', 'About', 'Tag', CFG.CFG_TAGS{8});
    
    % Left side, upper text
    hLp = uipanel('Parent',cfgWinHdl,...
        'Title','General Info',...
        'FontWeight', 'Bold',...
        'BackgroundColor',BgColor1,...
        'Units','normalized','Position',[.01 .8 .49 .2]);
    
    hSubjectText = uicontrol(hLp,'Style','text',...
        'Tag', CFG.CFG_TAGS{9},...
        'Units','normalized','Position',[.01 .7 .9 .2],...
        'HorizontalAlignment', 'left',...
        'BackgroundColor',BgColor1,...
        'String',['Subject: ' CFG.subject]);
    
    hDateText = uicontrol(hLp,'Style','text',...
        'Tag', CFG.CFG_TAGS{10},...
        'Units','normalized','Position',[.01 .5 .9 .2],...
        'HorizontalAlignment', 'left',...
        'BackgroundColor',BgColor1,...
        'String',['Date: ' CFG.date]);

    hTimeText = uicontrol(hLp,'Style','text',...
        'Tag', CFG.CFG_TAGS{11},...
        'Units','normalized','Position',[.01 .3 .9 .2],...
        'HorizontalAlignment', 'left',...
        'BackgroundColor',BgColor1,...
        'String',['Time: ' CFG.time]);
    
    hTimeText = uicontrol(hLp,'Style','text',...
        'Tag', CFG.CFG_TAGS{12},...
        'Units','normalized','Position',[.01 .1 .9 .2],...
        'HorizontalAlignment', 'left',...
        'BackgroundColor',BgColor1,...
        'String',['Path: ' CFG.path]);

    % Right side, upper text
    hRp = uipanel('Parent',cfgWinHdl,...
        'Title','Trial Info',...
        'FontWeight', 'Bold',...
        'BackgroundColor',BgColor1,...
        'Units','normalized','Position',[.51 .8 .49 .2]);
    
    hTrialsText = uicontrol(hRp,'Style','text',...
        'Tag', CFG.CFG_TAGS{13},...
        'Units','normalized','Position',[.01 .7 .9 .2],...
        'HorizontalAlignment', 'left',...
        'BackgroundColor',BgColor1,...
        'String',['Number of Trials: ' int2str(CFG.trials)]);
    
    hDropText = uicontrol(hRp,'Style','text',...
        'Tag', CFG.CFG_TAGS{14},...
        'Units','normalized','Position',[.01 .5 .9 .2],...
        'HorizontalAlignment', 'left',...
        'BackgroundColor',BgColor1,...
        'String',['Number of Dropped Trials: ' int2str(length(find(CFG.drop)))]); % Callback?

    hErrText = uicontrol(hRp,'Style','text',...
        'Tag', CFG.CFG_TAGS{15},...
        'Units','normalized','Position',[.01 .3 .9 .2],...
        'HorizontalAlignment', 'left',...
        'BackgroundColor',BgColor1,...
        'String',['Number of Error Trials: ' int2str(length(find(CFG.err)))]); % Callback?
    
    % Lower UI items
    hInitialHeader = uicontrol(cfgWinHdl,'Style','text',...
        'Tag', CFG.CFG_TAGS{16},...
        'Units','normalized','Position',[.01 .75 .49 .04],...
        'HorizontalAlignment', 'left',...
        'String',CFG.tTitle,...
        'BackgroundColor',BgColor2,...
        'FontWeight', 'bold');
    
    hFinalHeader = uicontrol(cfgWinHdl,'Style','text',...
        'Tag', CFG.CFG_TAGS{17},...
        'Units','normalized','Position',[.51 .75 .49 .04],...
        'HorizontalAlignment', 'left',...
        'String',CFG.tTitle,...
        'BackgroundColor',BgColor2,...
        'FontWeight', 'bold');
    
    hInitialListBox = uicontrol(cfgWinHdl,'Style','listbox',...
        'Tag', CFG.CFG_TAGS{18},...
        'Units','normalized','Position',[.01 .01 .49 .75],...
        'String',CFG.initial.table,...
        'BackgroundColor',BgColor2,...
        'Min', 0, 'Max', 1);
%         'Fontname', FWFONTNAME,...
%         'CallBack','');
        
    hFinalListBox = uicontrol(cfgWinHdl,'Style','listbox',...
        'Tag', CFG.CFG_TAGS{19},...
        'Units','normalized','Position',[.51 .01 .49 .75],...
        'String',CFG.final.table,...
        'BackgroundColor',BgColor2,...
        'Min', 0, 'Max', 1);
%         'Fontname', FWFONTNAME,...
%         'CallBack','');

end

figure(cfgWinHdl);

end